import { StyleSheet } from "react-native";
import COLORS from "../../../../constants/colors";

const gafete = StyleSheet.create({
	container: {
		flex: 1,
	},
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
	},
	modalContainer: {
		height: "40%",
		marginVertical: "2%",
		width: "90%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		flex: 1,
		width: "90%",
		justifyContent: "center",
		alignItems: "center",
	},
	titleContainer: {
		flex: 0.5,
		// height: "6%",
		width: "100%",
		marginTop: "4%",
		// borderWidth: 1,
		// borderRadius: 10,
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.black,
	},
	textContainer: {
		flex: 3.5,
		// borderWidth: 1,
		width: "100%",
		// marginTop: "2%",  
		marginBottom: "4%", 
		justifyContent: "center",
		alignItems: "flex-start",
	},
	text: {
		textAlign: "left",
		fontSize: 16,
		color: COLORS.black,
	},
	buttonContainer: {
		flex: 0.8,
		flexDirection: "row",
		marginBottom: "5%",
        // marginRight: "5%",
        // marginLeft: "5%",
        paddingHorizontal: "5%",
		width: "100%",
		justifyContent: "space-between",
		alignItems: "center",
		// borderWidth: 1,
	},
	button: {
		height: "90%",
		backgroundColor: COLORS.naranja,
		width: "30%",
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center",
	},
	textButton: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
});

const banorte = StyleSheet.create({
	container: {
		flex: 1,
	},
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
	},
	modalContainer: {
		// height: "80%",
		height: "62%",
		// marginVertical: "4%",
		// bottom: "14%",
		width: "90%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		flex: 1,
		width: "90%",
		justifyContent: "center",
		alignItems: "center",
	},
	titleContainer: {
		flex: 0.3,
		// height: "6%",
		width: "100%",
		marginTop: "4%",
		// borderWidth: 1,
		// borderRadius: 10,
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.black,
	},
	textContainer: {
		flex: 4,
		// height: "60%",
		// borderWidth: 1,
		width: "100%",
		marginTop: "2%",  
		marginBottom: "2%",  
		justifyContent: "center",
		alignItems: "flex-start",
	},
	textSubContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	text: {
		// flex: 1,
		fontSize: 16,
		textAlign: "left",
		// borderWidth: 1,
		color: COLORS.black,
	},
	subtext: {
		fontSize: 16,
		color: COLORS.black,
	},
	buttonContainer: {
		flex: 0.6,
		flexDirection: "row",
		marginBottom: "5%",
        // marginRight: "5%",
        // marginLeft: "5%",
        paddingHorizontal: "5%",
		width: "100%",
		justifyContent: "space-between",
		alignItems: "center",
		// borderWidth: 1,
	},
	button: {
		height: "80%",
		backgroundColor: COLORS.naranja,
		width: "30%",
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center",
	},
	textButton: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
	checkbox: {
		flex: 1,
		marginVertical: "1%",
	},
	checkboxGroup: {
		flex: 2,
		marginVertical: "3%",
	},
	checkboxText: {
		fontSize: 16,
		color: COLORS.black,
	},
	inputContainer: {
		flex: 0.5,
		marginBottom: "4%",
		paddingHorizontal: "3%",
		width: "100%",
		backgroundColor: COLORS.white,
		borderWidth: 1,
		borderRadius: 12,
		borderColor: "gray",
		justifyContent: "center",
		alignItems: "flex-start"
	},
	inputText: {
		fontSize: 14,
		color: COLORS.black,
		height: "100%", 
		width: "100%"
	}
});

const despensa = StyleSheet.create({
	container: {
		flex: 1,
	},
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
	},
	modalContainer: {
		// height: "80%",
		height: "45%",
		// marginVertical: "4%",
		// bottom: "14%",
		width: "90%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		flex: 1,
		width: "90%",
		justifyContent: "center",
		alignItems: "center",
	},
	titleContainer: {
		flex: 0.4,
		// height: "6%",
		width: "100%",
		marginTop: "4%",
		// borderWidth: 1,
		// borderRadius: 10,
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.black,
	},
	textContainer: {
		flex: 4,
		// height: "60%",
		// borderWidth: 1,
		width: "100%",
		marginTop: "2%",  
		marginBottom: "2%",  
		justifyContent: "center",
		alignItems: "flex-start",
	},
	textSubContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	text: {
		// flex: 1,
		fontSize: 16,
		textAlign: "left",
		// borderWidth: 1,
		color: COLORS.black,
	},
	subtext: {
		fontSize: 16,
		color: COLORS.black,
	},
	buttonContainer: {
		flex: 0.6,
		flexDirection: "row",
		marginTop: "5%",
		marginBottom: "6%",
        // marginRight: "5%",
        // marginLeft: "5%",
        paddingHorizontal: "5%",
		width: "100%",
		justifyContent: "space-between",
		alignItems: "center",
		// borderWidth: 1,
	},
	button: {
		height: "100%",
		backgroundColor: COLORS.naranja,
		width: "30%",
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center",
	},
	textButton: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
	checkbox: {
		flex: 1,
		marginVertical: "1%",
	},
	checkboxGroup: {
		flex: 2,
		marginVertical: "3%",
	},
	checkboxText: {
		fontSize: 16,
		color: COLORS.black,
	},
});

const confirm = StyleSheet.create({
	container: {
		flex: 1,
	},
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
	},
	modalContainer: {
		height: "30%",
		marginVertical: "2%",
		width: "70%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		flex: 1,
		width: "90%",
		justifyContent: "center",
		alignItems: "center",
	},
	animContainer: {
		flex: 2.5,
        width: "100%",
		top: "6%",
		// borderWidth: 1,
		justifyContent: "center",
		alignItems: "center",
	},
    anim: {
        width: "60%",
        height: "60%",
		// borderWidth: 1,
		// borderRadius: 10,
		justifyContent: "center",
		alignItems: "center",
    },
	textContainer: {
		flex: 2,
		// borderWidth: 1,
		width: "100%",
        marginBottom: "6%",
		justifyContent: "center",
		alignItems: "center",
	},
	text: {
		fontSize: 22,
		fontWeight: "500",
		color: COLORS.black,
        textAlign: "center",
		marginBottom: "3%",
	},
	lowerText: {
		fontSize: 14,
		color: COLORS.black,
        textAlign: "center"
	},
	button: {
		flex: 1,
        marginBottom: "5%",
		backgroundColor: "gray",
		width: "30%",
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
	},
	textButton: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
});

export { gafete, banorte, despensa, confirm };
