import { StyleSheet } from "react-native";
import COLORS from "../../../constants/colors";

const menu = StyleSheet.create({
	// Menu / Buttons properties
	container: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		width: "90%",
	},
	row: {
		flex: 1,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
});

const header = StyleSheet.create({
	container: {
		flex: 1,
		justifyContent: "center",
		alignContent: "flex-start",
		width: "95%",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	titleContainer: {
		height: "100%",
		width: "35%",
		borderBottomRightRadius: 50,
		backgroundColor: COLORS.main,
		justifyContent: "flex-start",
		alignItems: "flex-start",
		// borderWidth: 1,
		// borderColor: "black"
	},
	titleTextContainer: {
		left: "3%",
		top: "6%",
		height: "80%",
		width: "92%",
		justifyContent: "center",
		alignItems: "flex-start",
		// borderWidth: 1,
		// borderColor: "black"
	},
	title: {
		color: COLORS.white,
		fontWeight: "bold",
		fontSize: 11,
	},
});

const infopers = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	contentContainer: {
		flex: 19,
		justifyContent: "center",
		alignItems: "center",
		// height: "95%",
		width: "100%",
		// borderWidth: 1,
		// borderColor: "black"
	},
	scrollContainer: {
		flex: 1,
		width: "100%",
	},
	scrollContentContainer: {
		flexGrow: 1,
	},
	cardContainer: {
		flex: 1,
		marginTop: "3%",
		justifyContent: "flex-start",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	cardTitleContainer: {
		height: "12%",
		width: "94%",
		marginBottom: "3%",
		justifyContent: "center",
		alignItems: "flex-start",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	cardTitleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: "black",
	},
	cardInfoContainer: {
		height: "80%",
		width: "92%",
		padding: "4%",
		// marginBottom: "5%",
		justifyContent: "center",
		alignItems: "flex-start",
		backgroundColor: COLORS.flatlistBackground,
		borderRadius: 20,
	},
	cardInfoRowContainer: {
		flex: 1,
		bottom: "2%",
		justifyContent: "flex-start",
		alignItems: "center",
		flexDirection: "row",
		borderBottomWidth: 2,
		// borderWidth: 1,
		// borderColor: "purple"
	},
	cardInfoRowTitleContainer: {
		// flex: 2,
		width: "28%",
		height: "92%",
		marginBottom: "-1.5%",
		justifyContent: "center",
		alignItems: "flex-start",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	cardInfoRowTitleText: {
		fontSize: 12,
		fontWeight: "bold",
		color: "black",
	},
	cardInfoRowDataContainer: {
		flex: 8,
		paddingLeft: "1%",
		marginBottom: "-1.5%",
		justifyContent: "center",
		alignItems: "flex-start",
		// borderWidth: 1,
		// borderColor: "green"
	},
	cardInfoRowDataText: {
		fontSize: 12,
		color: "black",
		textAlign: "center",
	},
	cardInfoButton: {
		flex: 0.65,
		width: "33%",
		marginTop: "1.5%",
		backgroundColor: COLORS.naranja,
		justifyContent: "center",
		alignContent: "center",
		borderRadius: 50,
	},
	cardInfoButtonText: {
		fontSize: 9,
		fontWeight: "bold",
		color: COLORS.white,
		alignSelf: "center",
	},
});

const area = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	contentContainer: {
		flex: 19,
		justifyContent: "center",
		alignItems: "center",
		// height: "95%",
		width: "100%",
		// borderWidth: 1,
		// borderColor: "black"
	},
	cardContainer: {
		flex: 1,
		marginTop: "3%",
		justifyContent: "flex-start",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	titleContainer: {
		height: "12%",
		width: "94%",
		justifyContent: "center",
		alignItems: "flex-start",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: "black",
	},
	cardInfoContainer: {
		height: "80%",
		width: "92%",
		padding: "4%",
		// marginBottom: "5%",
		justifyContent: "center",
		alignItems: "flex-start",
		backgroundColor: COLORS.flatlistBackground,
		borderRadius: 20,
	},
});

const redes = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	contentContainer: {
		flex: 19,
		width: "95%",
		justifyContent: "center",
		alignItems: "center",
	},
	titleContainer: {
		height: "10%",
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// paddingLeft: "4%",
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
	},
	socialContainer: {
		height: "90%",
		width: "90%",
		justifyContent: "center",
		// borderWidth: 1,
		alignItems: "center",
	},
	stripContainer: {
		flex: 1,
		width: "100%",
		// borderWidth: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	stripImg: {
		height: "100%",
		width: "107%",
		right: "5.5%",
	},
	iconContainer: {
		position: "absolute",
		height: "60%",
		width: "16%",
		left: "9%",
		top: "24%",
		// borderWidth: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	linksContainer: {
		position: "absolute",
		flexDirection: "row",
		height: "60%",
		width: "72%",
		left: "28%",
		top: "22%",
		// borderWidth: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	linkContainer: {
		flex: 1,
		// borderWidth: 1,
		height: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	text: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.white,
	},
});

const directorio = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	contentContainer: {
		flex: 19,
		justifyContent: "center",
		alignItems: "center",
		// height: "95%",
		width: "95%",
		// borderWidth: 1,
		// borderColor: "black"
	},
	titleContainer: {
		height: "8%",
		width: "100%",
		justifyContent: "center",
		// borderWidth: 1,
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
	},
	scrollContainer: {
		height: "92%",
		// borderWidth: 1,
		width: "100%",
	},
	scrollContentContainer: {
		flexGrow: 1,
	},
	registroContainer: {
		width: "100%",
		marginTop: "2%",
		justifyContent: "flex-start",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "red"
	},
	registroRow: {
		height: "100%",
		width: "95%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	imgContainer: {
		flex: 1,
		height: "100%",
		justifyContent: "center",
		alignItems: "center",
		marginRight: "2%",
		// borderWidth: 1,
		// borderColor: "green"
	},
	img: {
		height: "100%",
		width: "100%",
	},
	infoContainer: {
		flex: 3.2,
		height: "100%",
		// flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		// paddingLeft: "2%",
		// borderWidth: 1,
	},
	stripImg: {
		height: "100%",
		width: "100%",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
		paddingLeft: "2%",
	},
	iconContainer: {
		justifyContent: "center",
		alignItems: "center",
		paddingLeft: "2%",
		paddingRight: "2%",
	},
	icon: {
		color: COLORS.white,
	},
	infoText: {
		fontSize: 14,
		fontWeight: "bold",
		color: COLORS.white,
	},
	divider: {
		height: 1,
		width: "100%",
		height: 1,
		backgroundColor: "grey",
		marginTop: "1%",
		marginHorizontal: "1%",
	},
});

const vacaciones = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	sectionContainer: {
		flex: 5,
		width: "100%",
		// borderWidth: 1,
		// borderColor: "black"
	},
	sectionTitleContainer: {
		flex: 2,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		paddingLeft: "4%",
	},
	sectionButtonContainer: {
		flex: 4,
		width: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		top: "1%",
	},
	historialContainer: {
		flex: 9,
		width: "85%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
});

const reciboNom = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	contentContainer: {
		flex: 19,
		width: "100%",
		justifyContent: "flex-start",
		alignItems: "center",
		// borderWidth: 1
	},
	sectionContainer: {
		// flex: 5,
		height: "24%",
		width: "100%",
		// borderWidth: 1,
		// borderColor: "black"
	},
	sectionTitleContainer: {
		flex: 2,
		width: "100%",
		top: "3%",
		justifyContent: "center",
		alignItems: "flex-start",
		paddingLeft: "4%",
	},
	sectionButtonContainer: {
		flex: 8,
		width: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
	},
	nominaContainer: {
		// flex: 14,
		height: "37.5%",
		marginTop: "1%",
		width: "95%",
		justifyContent: "flex-start",
		alignItems: "center",
		// borderWidth: 1
	},
	nominaHeader: {
		width: "100%",
		// height: "15%",
		flex: 1.7,
		borderRadius: 50,
		backgroundColor: COLORS.naranja,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	nominaYearContainer: {
		width: "20%",
		height: "100%",
		right: "4%",
		backgroundColor: "rgba(0, 0, 0, 0.2)",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
		borderRadius: 50,
		// borderWidth: 50,
	},
	nominaWeekContainer: {
		width: "30%",
		height: "100%",
		left: "10%",
		backgroundColor: "rgba(0, 0, 0, 0.2)",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
		borderRadius: 50,
		// borderWidth: 50,
	},
	nominaSearchIconContainer: {
		// height: "100%",
		paddingVertical: 6,
		paddingHorizontal: 6,
		justifyContent: "center",
		alignContent: "center",
		borderRadius: 50,
		backgroundColor: COLORS.main,
	},
	nominaSearchIcon: {
		color: COLORS.white,
	},
	nominaSearchText: {
		left: "30%",
		fontSize: 12,
		fontWeight: "bold",
		textAlign: "center",
		color: COLORS.white,
	},
	nominaCantidadContainer: {
		flex: 6,
		// height: "55%",
		width: "100%",
		// top: "3%",
		marginTop: "1.5%",
		// borderWidth: 1,
	},
	nominaCantidadElementContainer: {
		flex: 1,
		width: "100%",
		// height: "16%",
		justifyContent: "space-around",
		alignItems: "center",
		marginVertical: "1.0%",
		flexDirection: "row",
		backgroundColor: COLORS.flatlistElement2,
	},
	nominaCantidadBox: {
		width: "30%",
		height: "100%",
		right: "50%",
		justifyContent: "center",
		alignContent: "center",
	},
	nominaCantidadTitle: {
		fontSize: 17,
		color: COLORS.black,
		textAlign: "center",
	},
	nominaCantidad: {
		fontSize: 17,
		left: "25%",
		fontWeight: "bold",
		color: "black",
		textAlign: "center",
	},
	nominaGenerarContainer: {
		flex: 2.3,
		// height: "30%",
		width: "100%",
		// top: "3%",
		marginVertical: "1.5%",
		// borderWidth: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	nominaGenerarButton: {
		height: "100%",
		width: "50%",
		backgroundColor: COLORS.main,
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center",
		flexDirection: "row",
	},
	nominaGenerarText: {
		fontSize: 17,
		color: COLORS.white,
		textAlign: "center",
	},
	nominaGenerarIcon: {
		color: COLORS.white,
	},
});

const prenomina = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	contentContainer: {
		flex: 19,
		marginTop: "2%",
		// top: "4%",
		width: "95%",
		justifyContent: "flex-start",
		alignItems: "center",
		// borderWidth: 1
	},
	prenominaHeader: {
		width: "100%",
		height: "6%",
		borderRadius: 50,
		backgroundColor: COLORS.naranja,
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	prenominaYearContainer: {
		width: "20%",
		height: "100%",
		right: "4%",
		backgroundColor: "rgba(0, 0, 0, 0.2)",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
		borderRadius: 50,
		// borderWidth: 50,
	},
	prenominaWeekContainer: {
		width: "30%",
		height: "100%",
		left: "10%",
		backgroundColor: "rgba(0, 0, 0, 0.2)",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
		borderRadius: 50,
		// borderWidth: 50,
	},
	prenominaSearchIconContainer: {
		paddingVertical: 6,
		paddingHorizontal: 6,
		justifyContent: "center",
		alignContent: "center",
		borderRadius: 50,
		backgroundColor: COLORS.main,
	},
	prenominaSearchIcon: {
		color: COLORS.white,
	},
	prenominaSearchText: {
		left: "30%",
		fontSize: 12,
		fontWeight: "bold",
		textAlign: "center",
		color: COLORS.white,
	},
	prenominaContainer: {
		height: "40%",
		// flex: 3.5,
		width: "100%",
		marginTop: "3%",
		// borderWidth: 1,
	},
	prenominaCantidadElementContainer: {
		flex: 1,
		width: "100%",
		// height: "8%",
		justifyContent: "space-around",
		alignItems: "center",
		marginVertical: "1.0%",
		flexDirection: "row",
		backgroundColor: COLORS.flatlistElement2,
	},
	prenominaCantidadBox: {
		width: "30%",
		height: "100%",
		right: "50%",
		justifyContent: "center",
		alignContent: "center",
	},
	prenominaCantidadTitle: {
		fontSize: 17,
		color: COLORS.black,
		textAlign: "center",
	},
	prenominaCantidad: {
		fontSize: 17,
		left: "25%",
		fontWeight: "bold",
		color: "black",
		textAlign: "center",
	},
	buttonContainer: {
		width: "30%",
		// flex: 1,
		height: "10%",
		marginTop: "2%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
	},
	buttonBackground: {
		width: "100%",
		height: "100%",
		borderRadius: 200,
		justifyContent: "center",
		alignItems: "center",
		overflow: "hidden",
		position: "absolute",
	},
	buttonText: {
		fontSize: 12,
		color: COLORS.white,
		fontWeight: "bold",
	},
	detalleHeader: {
		width: "100%",
		height: "15%",
		backgroundColor: COLORS.white,
		justifyContent: "center",
		borderRadius: "12%",
		borderWidth: 1,
		borderColor: COLORS.flatlistElement1,
		alignItems: "center",
	},
	detalleHeaderWeekYearRow: {
		flex: 1,
		width: "100%",
		backgroundColor: COLORS.naranja,
		borderRadius: "10%",
		justifyContent: "center",
		alignItems: "center",
		flexDirection: "row",
	},
	detalleHeaderDaysRow: {
		flex: 1.5,
		width: "97%",
		// backgroundColor: COLORS.w,
		justifyContent: "center",
		alignItems: "center",
		flexDirection: "row",
		// borderWidth: 1,
	},
	detalleDayButton: {
		flex: 1,
		paddingVertical: "1.5%",
		paddingHorizontal: "0.5%",
		marginHorizontal: "0.7%",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 4,
		// borderWidth: 1,
	},
	detalleSelectedDayButton: {
		flex: 1.5,
		paddingVertical: "1.5%",
		paddingHorizontal: "0.5%",
		marginHorizontal: "0.7%",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 4,
		backgroundColor: COLORS.naranja,
		// borderWidth: 1,
	},
	detalleDayButtonText: {
		fontSize: 13,
		// fontWeight: "bold",
		color: "black",
	},
	detalleSelectedDayButtonText: {
		fontSize: 13,
		// fontWeight: "bold",
		color: COLORS.white,
	},
	detalleDayContainer: {
		height: "62%",
		width: "100%",
		padding: "2%",
		marginTop: "6%",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: COLORS.flatlistElement1,
		borderRadius: 6,
	},
	detalleDaysDescContainer: {
		flex: 1,
		// height: "6%",
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
	},
	detalleDaysDescText: {
		fontSize: 13,
		color: "black",
		fontWeight: "bold",
	},
	detalleHabilContainer: {
		flex: 1,
		// height: "6%",
		width: "20%",
		borderRadius: 12,
		marginTop: "2%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.black,
		// borderWidth: 1,
	},
	detalleHabilText: {
		fontSize: 14,
		color: COLORS.white,
		fontWeight: "bold",
	},
	detalleDataContainer: {
		// height: "40%",
		flex: 3.5,
		width: "100%",
		marginTop: "3%",
		// borderWidth: 1,
	},
});

const solicitudes = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	sectionContainer: {
		flex: 19,
		width: "100%",
		justifyContent: "flex-start",
		alignItems: "center",
	},
	sectionTitleContainer: {
		height: "10%",
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		paddingLeft: "4%",
	},
	sectionButtonContainer: {
		height: "15%",
		width: "85%",
		top: "6%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
});

const prestamos = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	contentContainer: {
		flex: 19,
		justifyContent: "center",
		alignItems: "center",
		width: "94%",
		marginTop: "2%",
		borderRadius: 10,
		// borderTopLeftRadius: 10,
		// borderTopRightRadius: 10,
		// borderBottomLeftRadius: 10,
		// borderBottomRightRadius: 10,
		backgroundColor: COLORS.flatlistBackground,
		// borderWidth: 1,
		// borderColor: "black"
	},
	titleBar: {
		flex: 1,
		width: "100%",
		borderRadius: 100,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.naranja,
	},
	titleContainer: {
		height: "80%",
		width: "38%",
		borderRadius: 100,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(0, 0, 0, 0.2)",
	},
	titleText: {
		fontSize: 12,
		fontWeight: "bold",
		color: "white",
	},
	infoContainer: {
		flex: 19,
		width: "95%",
		justifyContent: "center",
		alignItems: "center",
	},
	dataContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		// borderWidth: 1,
		marginTop: "4%",
	},
	dataRowContainer: {
		flex: 1,
		height: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		marginTop: "1%",

		// borderWidth: 1,
	},
	dataTextContainer: {
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		// borderWidth: 1,
	},
	dataRowTextContainer: {
		justifyContent: "flex-start",
		alignItems: "center",
		// borderWidth: 1,
	},
	dataFieldContainer: {
		height: "65%",
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		paddingLeft: "3%",
		marginVertical: "1%",
		borderWidth: 1,
		borderColor: COLORS.grey,
		borderRadius: 10,
		backgroundColor: COLORS.white,
	},
	dataRowFieldContainer: {
		flex: 1,
		height: "65%",
		marginHorizontal: "4%",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: COLORS.grey,
		borderRadius: 10,
		backgroundColor: COLORS.white,
	},
	dataText: {
		fontSize: 15,
		fontWeight: "bold",
		color: "black",
	},
	dataFieldText: {
		fontSize: 15,
		color: "black",
	},
	buttonContainer: {
		flex: 0.5,
		paddingHorizontal: "12%",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 100,
		marginTop: "1%",
		marginBottom: "1%",
		backgroundColor: COLORS.naranja,
	},
	buttonText: {
		fontSize: 13,
		fontWeight: "bold",
		color: "white",
	},
	agreementContainer: {
		flex: 1.5,
		marginTop: "2%",
		flexDirection: "row",
		width: "100%",
		// borderWidth: 1,
	},
	agreementTextContainer: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	agreementText: {
		fontSize: 12,
		color: COLORS.black,
	},
	bouncyCheckbox: {},
});

const reposiciones = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	sectionContainer: {
		flex: 19,
		width: "100%",
		justifyContent: "flex-start",
		alignItems: "center",
	},
	sectionTitleContainer: {
		height: "10%",
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		paddingLeft: "4%",
	},
	sectionButtonContainer: {
		flex: 1,
		// height: "100%",
		width: "80%",
		// top: "3%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
	},
});

const linea = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	sectionContainer: {
		flex: 19,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
	},
	background: {
		position: "absolute",
		right: "25%",
		height: "100%",
		width: "100%",
	},
	sectionTitleContainer: {
		flex: 1.2,
		// height: "10%",
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		paddingLeft: "4%",
		// borderWidth: 1,
	},
	sectionAnimation: {
		flex: 7.4,
		// height: "75%",
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	animationContainer: {
		height: "100%",
		width: "75%",
		right: "9%",
		bottom: "4%",
		alignSelf: "flex-start",
		justifyContent: "center",
		alignItems: "center",
		zIndex: 2,
		// borderWidth: 1,
	},
	textContainer: {
		position: "absolute",
		// flex: 1,
		height: "22%",
		width: "80%",
		bottom: "30%",
		paddingLeft: "6%",
		borderTopLeftRadius: 10,
		borderBottomLeftRadius: 10,
		// top: "10%",
		alignSelf: "flex-end",
		justifyContent: "center",
		alignItems: "flex-end",
		backgroundColor: COLORS.white,
		// zIndex: 1,
		// borderWidth: 1,
	},
	textBox: {
		width: "65%",
		height: "80%",
		marginRight: "2%",
		justifyContent: "center",
		alignItems: "flex-end",
		// borderWidth: 1,
	},
	text: {
		fontSize: 13,
		color: COLORS.black,
		textAlign: "right",
		fontWeight: "500",
	},
	sectionButtonContainer: {
		flex: 1.4,
		// height: "15%",
		width: "95%",
		// borderWidth: 1,
		// top: "6%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
});

const polizas = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	contentContainer: {
		flex: 19,
		justifyContent: "center",
		alignItems: "center",
		// height: "95%",
		width: "100%",
		// borderWidth: 1,
		// borderColor: "black"
	},
	scrollContainer: {
		flex: 1,
		width: "100%",
	},
	scrollContentContainer: {
		flexGrow: 1,
	},
});

const opiniones = StyleSheet.create({
	container: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "purple"
	},
	contentContainer: {
		flex: 19,
		justifyContent: "center",
		alignItems: "center",
		width: "94%",
		marginTop: "2%",
		borderRadius: 10,
		// borderTopLeftRadius: 10,
		// borderTopRightRadius: 10,
		// borderBottomLeftRadius: 10,
		// borderBottomRightRadius: 10,
		backgroundColor: COLORS.flatlistBackground,
		// borderWidth: 1,
		// borderColor: "black"
	},
	titleBar: {
		flex: 1,
		width: "100%",
		flexDirection: "row",
		borderRadius: 100,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.naranja,
		// borderWidth: 1,
	},
	iconContainer: {
		position: "absolute",
		height: "100%",
		width: "10%",
		alignSelf: "flex-start",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 100,
		backgroundColor: COLORS.main,
	},
	icon: {
		color: COLORS.white,
	},
	titleContainer: {
		height: "100%",
		width: "70%",
		borderRadius: 100,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(0, 0, 0, 0.2)",
	},
	titleText: {
		fontSize: 12,
		fontWeight: "bold",
		color: "white",
	},
	infoContainer: {
		flex: 16,
		width: "95%",
		justifyContent: "flex-start",
		alignItems: "center",
	},
	dataContainer: {
		height: "50%",
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// marginTop: "2%",
	},
	dataTitleContainer: {
		flex: 2,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		marginVertical: "3%",
	},
	dataTitleText: {
		fontSize: 19,
		fontWeight: "bold",
		color: "black",
	},
	dataFieldContainer: {
		flex: 10,
		width: "100%",
		justifyContent: "flex-start",
		alignItems: "flex-start",
		borderRadius: 15,
		padding: "3%",
		backgroundColor: COLORS.white,
	},
	dataFieldText: {
		width: "100%",
		height: "100%",
		textAlignVertical: "top",
		fontSize: 14,
		fontWeight: "bold",
		color: COLORS.black,
		textAlign: "left",
	},
	buttonContainer: {
		flex: 0.2,
		paddingHorizontal: "12%",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 100,

		marginTop: "5%",
		backgroundColor: COLORS.naranja,
	},
	buttonText: {
		fontSize: 13,
		fontWeight: "bold",
		color: "white",
	},
});

export {
	menu,
	header,
	infopers,
	area,
	redes,
	directorio,
	vacaciones,
	reciboNom,
	prenomina,
	solicitudes,
	prestamos,
	reposiciones,
	linea,
	polizas,
	opiniones,
};
