import { StyleSheet } from "react-native";
import COLORS from "../../../../constants/colors";

const cartaModal = StyleSheet.create({
	container: {
		flex: 1,
	},
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
	},
	modalContainer: {
		height: "auto",
		// height: "80%",
		// height: "auto",
		// marginVertical: "4%",
		// bottom: "14%",
		width: "90%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		height: "auto",
		width: "90%",
		justifyContent: "center",
		alignItems: "center",
	},
	titleContainer: {
		height: 30,
		// flex: 0.3,
		// height: "6%",
		width: "100%",
		marginTop: "4%",
		// borderWidth: 1,
		// borderRadius: 10,
		justifyContent: "flex-start",
		alignItems: "flex-start",
		// borderWidth: 1,
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.black,
	},
	textContainer: {
		// height: 450,
		// flex: 4,
		// height: "60%",
		// borderWidth: 1,
		paddingTop: 10,
		paddingBottom: 10,
		width: "100%",
		marginTop: "2%",
		// marginBottom: "1%",
		justifyContent: "center",
		alignItems: "flex-start",
		// borderWidth: 1,
	},
	textSubContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	text: {
		// flex: 1,
		fontSize: 16,
		textAlign: "left",
		// borderWidth: 1,
		color: COLORS.black,
	},
	subtext: {
		fontSize: 16,
		color: COLORS.black,
	},
	buttonContainer: {
		height: 55,
		// flex: 0.6,
		flexDirection: "row",
		marginBottom: "3%",
		// marginRight: "5%",
		// marginLeft: "5%",
		paddingHorizontal: "5%",
		width: "100%",
		justifyContent: "space-between",
		alignItems: "center",
		// borderWidth: 1,
	},
	button: {
		height: "80%",
		backgroundColor: COLORS.naranja,
		width: "30%",
		borderRadius: 15,
		justifyContent: "center",
		alignItems: "center",
	},
	textButton: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
	checkbox: {
		flex: 1,
		marginVertical: "1%",
	},
	checkboxGroup: {
		flex: 2,
		width: "100%",
		marginVertical: "3%",
	},
	checkboxText: {
		fontSize: 16,
		color: "black",
		textDecorationLine: "underline",
	},
	inputText: {
		fontSize: 16,
		textAlign: "left",
		// borderWidth: 1,
		color: COLORS.black,
	},
	inputTextContainer: {
		flex: 0.3,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	inputContainer: {
		height: 90,
		// flex: 0.5,
		marginBottom: "4%",
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		// borderWidth: 1,
	},
	inputField: {
		// height: 50,
		flex: 0.7,
		marginTop: "3%",
		paddingHorizontal: "3%",
		width: "100%",
		backgroundColor: COLORS.white,
		borderWidth: 1,
		borderRadius: 12,
		borderColor: "gray",
		justifyContent: "center",
		alignItems: "flex-start",
	},
});

export { cartaModal };
