import { StyleSheet } from "react-native";
import COLORS from "../../../../constants/colors";

const solVacaciones = StyleSheet.create({
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.3)",
	},
	modalContainer: {
		height: "60%",
		marginVertical: "2%",
		width: "80%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		flex: 1,
		width: "90%",
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	titleContainer: {
		flex: 10,
		// height: "6%",
		width: "100%",
		top: "3%",
		// height: "4%",
		borderRadius: 10,
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.black,
	},
	cantidadContainer: {
		flex: 30,
		marginTop: "3%",
		// height: "20%",
		width: "100%",
	},
	cantidadElementContainer: {
		top: "5%",
		width: "100%",
		height: "22%",
		justifyContent: "space-around",
		alignItems: "center",
		marginVertical: "1.0%",
		flexDirection: "row",
		backgroundColor: COLORS.flatlistElement2,
	},
	cantidadBox: {
		width: "40%",
		height: "100%",
		justifyContent: "center",
		alignContent: "center",
	},
	cantidadTitle: {
		fontSize: 14,
		color: COLORS.black,
		textAlign: "left",
	},
	cantidad: {
		fontSize: 17,
		fontWeight: "bold",
		color: "black",
		textAlign: "right",
	},
	fechasContainer: {
		flex: 15,
		// height: "9%",
		width: "100%",
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
	},
	fechaContainer: {
		height: "100%",
		width: "36%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "gray",
		// borderRadius: 10,
	},
	diasContainer: {
		flex: 3,
		width: "28%",
		justifyContent: "center",
		alignItems: "center",
	},
	fechaTitleContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	fechaTitle: {
		fontSize: 14,
		fontWeight: "bold",
		color: "black",
	},
	fechaDateContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: "gray",
		borderRadius: 10,
	},
	fechaButton: {
		height: "100%",
		width: "100%",
		// backgroundColor: COLORS.naranja,
		// borderRadius: 50,
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
	},
	fechaText: {
		left: "10%",
		fontSize: 12,
		color: COLORS.black,
	},
	iconContainer: {

	},
	icon: {
		borderStartWidth: 1,
		borderColor: "gray",
		left: "15%"
	},
	diasContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		
	},
	diasBottomContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",		
		flexDirection: "row",
	},
	diasSeparatorContainer: {
		flex: 1,
		width: "35%",
		justifyContent: "center",
		alignItems: "center",
	},
	diasSeparator: {
		fontSize: 20,
		color: COLORS.black,
	},
	diasTextContainer: {
		height: "100%",
		width: "30%",
		borderWidth: 1,
		borderColor: "gray",
		borderRadius: 10,
		justifyContent: "center",
		alignItems: "center",
	},
	diasText: {
		fontSize: 12,
		color: COLORS.black,
	},
	comentariosContainer: {
		flex: 35,
		// height: "30%",
		width: "100%",
		marginVertical: "4%",		
		justifyContent: "flex-start",
		alignItems: "flex-start"
	},
	comentariosTitle: {
		flex: 1,
		fontSize: 14,
		fontWeight: "bold",
		color: "black",
	},
	comentariosTitleText: {
		flex: 4,
		width: "100%",
		borderWidth: 1,
		borderColor: COLORS.flatlistElement2,
		borderRadius: 10,
		fontSize: 12,
		padding: "2%",
		color: "black",
		textAlignVertical: "top"
	},
	exitButton: {
		flex: 10,
		// height: "10%",
		backgroundColor: COLORS.naranja,
		alignSelf: "flex-end",
		// height: "6%",
		width: "30%",
		marginBottom: "3%",
		marginRight: "3%",
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.naranja,
	},
	textExitButton: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
});

const solPermisos = StyleSheet.create({
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.3)",
	},
	modalContainer: {
		height: "60%",
		marginVertical: "2%",
		width: "80%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		flex: 1,
		width: "90%",
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	titleContainer: {
		flex: 10,
		// height: "6%",
		width: "100%",
		top: "3%",
		// height: "4%",
		borderRadius: 10,
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.black,
	},
	fechasContainer: {
		flex: 15,
		// height: "9%",
		width: "100%",
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
	},
	fechaContainer: {
		height: "100%",
		width: "36%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "gray",
		// borderRadius: 10,
	},
	diasContainer: {
		flex: 3,
		width: "28%",
		justifyContent: "center",
		alignItems: "center",
	},
	fechaTitleContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	fechaTitle: {
		fontSize: 14,
		fontWeight: "bold",
		color: "black",
	},
	fechaDateContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: "gray",
		borderRadius: 10,
	},
	fechaButton: {
		height: "100%",
		width: "100%",
		// backgroundColor: COLORS.naranja,
		// borderRadius: 50,
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
	},
	fechaText: {
		left: "10%",
		fontSize: 12,
		color: COLORS.black,
	},
	iconContainer: {

	},
	icon: {
		borderStartWidth: 1,
		borderColor: "gray",
		left: "10%"
	},
	diasContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		
	},
	diasBottomContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",		
		flexDirection: "row",
	},
	diasSeparatorContainer: {
		flex: 1,
		width: "35%",
		justifyContent: "center",
		alignItems: "center",
	},
	diasSeparator: {
		fontSize: 20,
		color: COLORS.black,
	},
	diasTextContainer: {
		height: "100%",
		width: "30%",
		borderWidth: 1,
		borderColor: "gray",
		borderRadius: 10,
		justifyContent: "center",
		alignItems: "center",
	},
	diasText: {
		fontSize: 12,
		color: COLORS.black,
	},	
	tipoContainer: {
		flex: 15,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start"
	},
	tipoTitleContainer: {
		flex: 1,
		width: "100%",
		marginTop: "3%",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	tipoTitleText: {
		fontSize: 14,
		color: COLORS.black,
		fontWeight: "bold"
	},
	tipoBox: {
		flex: 1,
		width: "50%",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: "gray",
		borderRadius: 10
	},
	tipoText: {
		fontSize: 12,
		color: COLORS.black,
	},
	comentariosContainer: {
		flex: 30,
		// height: "30%",
		width: "100%",
		marginVertical: "4%",		
		justifyContent: "flex-start",
		alignItems: "flex-start"
	},
	comentariosTitle: {
		flex: 1,
		fontSize: 14,
		fontWeight: "bold",
		color: "black",
	},
	comentariosTitleText: {
		flex: 4,
		width: "100%",
		borderWidth: 1,
		borderColor: COLORS.flatlistElement2,
		borderRadius: 10,
		fontSize: 12,
		padding: "2%",
		color: "black",
		textAlignVertical: "top"
	},
	exitButton: {
		flex: 10,
		// height: "10%",
		backgroundColor: COLORS.naranja,
		alignSelf: "flex-end",
		// height: "6%",
		width: "30%",
		marginBottom: "3%",
		marginRight: "3%",
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.naranja,
	},
	textExitButton: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
});

export { solPermisos, solVacaciones };
