import { StyleSheet } from "react-native";
import COLORS from "../../../../constants/colors";

const solVacaciones = StyleSheet.create({
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.3)",
	},
	modalContainer: {
		height: "auto",
		// height: "60%",
		marginVertical: "2%",
		width: "80%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		// flex: 1,
		height: "auto",
		width: "90%",
		paddingVertical: 15,
		justifyContent: "center",
		alignItems: "center",
	},
	titleContainer: {
		// paddingVertical: 5,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		// borderWidth: 1
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.black,
	},
	cantidadContainer: {
		// flex: 30,
		height: 110,
		marginTop: 15,
		// height: "20%",
		justifyContent: "center",
		alignItems: "center",
		width: "100%",
		// borderWidth: 1
	},
	cantidadElementContainer: {
		// top: "5%",
		flex: 1,
		width: "100%",
		justifyContent: "space-around",
		alignItems: "center",
		marginVertical: "1%",
		flexDirection: "row",
		backgroundColor: COLORS.flatlistElement2,
	},
	cantidadBox: {
		width: "40%",
		height: "100%",
		justifyContent: "center",
		alignContent: "center",
	},
	cantidadTitle: {
		fontSize: 14,
		color: COLORS.black,
		textAlign: "left",
	},
	cantidad: {
		fontSize: 17,
		fontWeight: "bold",
		color: "black",
		textAlign: "right",
	},
	fechasContainer: {
		// flex: 15,
		height: 80,
		// height: "9%",
		width: "100%",
		marginTop: 15,
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
		// borderWidth: 1,
	},
	fechaContainer: {
		height: "100%",
		width: "36%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "gray",
		// borderRadius: 10,
	},
	diasContainer: {
		flex: 3,
		width: "28%",
		justifyContent: "center",
		alignItems: "center",
	},
	fechaTitleContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	fechaTitle: {
		fontSize: 14,
		fontWeight: "bold",
		color: "black",
	},
	fechaDateContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: "gray",
		borderRadius: 10,
	},
	fechaButton: {
		height: "100%",
		width: "100%",
		// backgroundColor: COLORS.naranja,
		// borderRadius: 50,
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
	},
	fechaText: {
		left: "10%",
		fontSize: 12,
		color: COLORS.black,
	},
	iconContainer: {},
	icon: {
		borderStartWidth: 1,
		borderColor: "gray",
		left: 2,
		// right: ,
	},
	diasContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	diasBottomContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		flexDirection: "row",
	},
	diasSeparatorContainer: {
		flex: 1,
		width: "35%",
		justifyContent: "center",
		alignItems: "center",
	},
	diasSeparator: {
		fontSize: 20,
		color: COLORS.black,
	},
	diasTextContainer: {
		height: "100%",
		width: "30%",
		borderWidth: 1,
		borderColor: "gray",
		borderRadius: 10,
		justifyContent: "center",
		alignItems: "center",
	},
	diasText: {
		fontSize: 12,
		color: COLORS.black,
	},
	comentariosContainer: {
		// flex: 35,
		height: 150,
		// height: "30%",
		width: "100%",
		marginTop: 15,
		// marginVertical: "4%",
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	comentariosTitle: {
		flex: 1,
		fontSize: 14,
		fontWeight: "bold",
		color: "black",
	},
	comentariosText: {
		flex: 4,
		width: "100%",
		borderWidth: 1,
		borderColor: COLORS.flatlistElement2,
		borderRadius: 10,
		fontSize: 12,
		padding: "2%",
		color: "black",
		textAlignVertical: "top",
	},
	buttonsContainer: {
		height: 40,
		width: "100%",
		marginTop: 15,
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
	},
	button: {
		height: "100%",
		// width: "30%",
		justifyContent: "center",
		alignItems: "center",
		paddingHorizontal: 18,
		// borderWidth: 1,
		borderRadius: 15,
	},
	buttonText: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
});

const solPermisos = StyleSheet.create({
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.3)",
	},
	modalContainer: {
		height: "60%",
		// marginVertical: "2%",
		width: "80%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		flex: 1,
		width: "90%",
		paddingVertical: "4%",
		justifyContent: "center",
		alignItems: "center",
	},
	titleContainer: {
		flex: 10,
		// height: "6%",
		width: "100%",
		// top: "3%",
		// height: "4%",
		borderRadius: 10,
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.black,
	},
	fechasContainer: {
		flex: 15,
		// height: "9%",
		width: "100%",
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
		// borderWidth: 1,
	},
	fechaContainer: {
		flex: 1.5,
		height: "100%",
		// width: "40%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "gray",
		// borderRadius: 10,
	},
	diasContainer: {
		flex: 1,
		height: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1
	},
	fechaTitleContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	fechaTitle: {
		fontSize: 14,
		fontWeight: "bold",
		color: "black",
	},
	fechaDateContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: "gray",
		borderRadius: 10,
	},
	fechaButton: {
		height: "100%",
		width: "100%",
		// backgroundColor: COLORS.naranja,
		// borderRadius: 50,
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
		// borderWidth: 1
	},
	fechaText: {
		left: 20,
		fontSize: 15,
		color: COLORS.black,
	},
	iconContainer: {},
	icon: {
		position: "absolute",
		borderStartWidth: 1,
		borderColor: "gray",
		right: 8,
	},
	diasBottomContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		flexDirection: "row",
	},
	diasSeparatorContainer: {
		flex: 1,
		width: "35%",
		justifyContent: "center",
		alignItems: "center",
	},
	diasSeparator: {
		fontSize: 20,
		color: COLORS.black,
	},
	diasTextContainer: {
		height: "100%",
		width: "40%",
		borderWidth: 1,
		borderColor: "gray",
		borderRadius: 10,
		justifyContent: "center",
		alignItems: "center",
	},
	diasTextField: {
		height: "100%",
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		textAlign: "center",
		fontSize: 15,
		color: COLORS.black,
	},
	tipoContainer: {
		flex: 17,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		// borderWidth: 1
	},
	tipoTitleContainer: {
		flex: 1,
		width: "100%",
		marginTop: "3%",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	tipoTitleText: {
		fontSize: 14,
		color: COLORS.black,
		fontWeight: "bold",
	},
	tipoField: {
		flex: 1,
		width: "70%",
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: "gray",
		borderRadius: 10,
		// backgroundColor: "red"
	},
	tipoIconContainer: {
		position: "absolute",
		right: -2,
		top: 2,
		height: "100%",
		width: "20%",
		// justifyContent: "center",
		// alignItems: "center",
		// borderWidth: 1,
		// right: 4
	},
	tipoText: {
		right: 10,
		fontSize: 14,
		color: COLORS.black,
	},
	comentariosContainer: {
		flex: 30,
		// height: "30%",
		width: "100%",
		marginTop: "7%",
		marginBottom: "4%",
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	comentariosTitle: {
		flex: 1,
		fontSize: 14,
		fontWeight: "bold",
		color: "black",
	},
	comentariosTitleText: {
		flex: 4.5,
		width: "100%",
		borderWidth: 1,
		borderColor: COLORS.flatlistElement2,
		borderRadius: 10,
		fontSize: 14,
		padding: "2%",
		color: "black",
		textAlignVertical: "top",
	},
	buttonsContainer: {
		flex: 8,
		width: "100%",
		justifyContent: "space-around",
		alignItems: "center",
		flexDirection: "row",
		// borderWidth: 1
	},
	button: {
		// width: "30%",
		height: "100%",
		borderRadius: 15,
		paddingVertical: 5,
		paddingHorizontal: 15,
		justifyContent: "center",
		alignItems: "center",
	},
	buttonText: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
});

const dataModal = StyleSheet.create({
	container: {
		position: "absolute",
		flex: 1,
	},
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
	},
	modalContainer: {
		top: "40%",
		alignSelf: "center",
		position: "absolute",
		height: "25%",
		// marginVertical: "2%",
		width: "80%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		height: "100%",
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	picker: {
		// padding: 4,
		// marginTop: 10,
		// height: 50,
		width: "95%",
		paddingLeft: 10,
		// backgroundColor: "red",
		// width: "100%",
		// height: "100%",
		// marginBottom: 2,
		// paddingBottom: 2,
		// fontSize: 15,
		// color: "black",
		// justifyContent: "center",
		// alignContent: "center",
		// borderWidth: 1,
		// zIndex: 1,
	},
	pickerItem: {
		color: "white",
		// borderWidth: 1,
		fontSize: 18,
		fontFamily: "Montserrat-Medium",
	},
});

export { solPermisos, solVacaciones, dataModal };
