import { StyleSheet } from "react-native";
import COLORS from "../../../../constants/colors";

const historialModal = StyleSheet.create({
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "flex-start",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
		// borderRadius: 20,
	},
	modalContainer: {
		flex: 1,
		marginVertical: "8%",
		top: "2%",
		width: "90%",
		justifyContent: "flex-start",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 0.95)",
		borderRadius: 20,
	},
	titleContainer: {
		flex: 4,
		backgroundColor: COLORS.naranja,
		// height: "4%",
		width: "95%",
		marginTop: "2%",
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
	},
	textTitle: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
	searchContainer: {
		flex: 8,
		// height: "8%",
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	searchFieldContainer: {
		height: "60%",
		width: "40%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
		borderRadius: 50,
	},
	searchIconContainer: {
		height: "100%",
		width: "25%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.main,
		borderRadius: 50,
	},
	searchIcon: {
		color: COLORS.white,
	},
	searchYearContainer: {
		flex: 6,
		justifyContent: "center",
		alignItems: "center",
	},
	searchYearText: {
		fontSize: 17,
		// left: "-2%",
		fontWeight: "bold",
		color: COLORS.white,
	},
	searchArrowContainer: {
		flex: 2,
		justifyContent: "center",
		alignItems: "center",
		top: "2%",
		// borderWidth: 1,
		// alignSelf: "flex-end",
		width: "100%",
		// backgroundColor: "white"
		// flex: 1,
	},
	listContainer: {
		flex: 82,
		width: "100%",
		backgroundColor: COLORS.flatlistBackground,
		justifyContent: "center",
		alignItems: "center",
		marginBottom: "2.5%",
	},
	listTitleContainer: {
		flex: 1,
		width: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	listTitleText: {
		fontSize: 13,
		textAlign: "center",
		fontWeight: "bold",
		color: "black",
	},
	listElementsContainer: {
		flex: 9,
		width: "100%",
	},
	listElementBoxContainer: {
		flex: 1,
	},
	listElement: {
		padding: "1%",
		marginVertical: "2%",
		width: "100%",
		backgroundColor: COLORS.flatlistElement1,
		flexDirection: "row",
	},
	listElementText: {
		fontSize: 12,
		textAlign: "center",
		color: "black",
	},
	exitButton: {
		flex: 6,
		backgroundColor: COLORS.naranja,
		alignSelf: "flex-end",
		// height: "6%",
		width: "30%",
		marginBottom: "3%",
		marginRight: "3%",
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.naranja,
	},
	textExitButton: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
});

const yearModal = StyleSheet.create({
	container: {
		position: "absolute",
		flex: 1,
	},
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
	},
	modalContainer: {
		top: "40%",
		alignSelf: "center",
		position: "absolute",
		height: "25%",
		// marginVertical: "2%",
		width: "80%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		height: "100%",
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	picker: {
		width: "100%",
		height: "100%",
	},
});

const signatureModal = StyleSheet.create({
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
		// borderRadius: 20,
	},
	modalContainer: {
		// flex: 1,
		height: "auto",
		marginVertical: "5%",
		// top: "2%",
		width: "90%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 0.95)",
		borderRadius: 20,
	},
	contentContainer: {
		// flex: 1,
		height: "100%",
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1
	},
	titleContainer: {
		// flex: 1,
		height: "7%",
		backgroundColor: COLORS.naranja,
		// height: "4%",
		width: "95%",
		// marginTop: "2%",
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
	},
	textTitle: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
	searchContainer: {
		flex: 8,
		// height: "8%",
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
	},
	searchFieldContainer: {
		height: "60%",
		width: "40%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
		borderRadius: 50,
	},
	searchIconContainer: {
		height: "100%",
		width: "25%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.main,
		borderRadius: 50,
	},
	searchIcon: {
		color: COLORS.white,
	},
	searchYearContainer: {
		flex: 6,
		justifyContent: "center",
		alignItems: "center",
	},
	searchYearText: {
		fontSize: 17,
		// left: "-2%",
		fontWeight: "bold",
		color: COLORS.white,
	},
	searchArrowContainer: {
		flex: 2,
		justifyContent: "center",
		alignItems: "center",
		top: "2%",
		// borderWidth: 1,
		// alignSelf: "flex-end",
		width: "100%",
		// backgroundColor: "white"
		// flex: 1,
	},
	listContainer: {
		flex: 82,
		width: "100%",
		backgroundColor: COLORS.flatlistBackground,
		justifyContent: "center",
		alignItems: "center",
		marginBottom: "2.5%",
	},
	listTitleContainer: {
		flex: 1,
		width: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	listTitleText: {
		fontSize: 13,
		textAlign: "center",
		fontWeight: "bold",
		color: "black",
	},
	listElementsContainer: {
		flex: 9,
		width: "100%",
	},
	listElementBoxContainer: {
		flex: 1,
	},
	listElement: {
		padding: "1%",
		marginVertical: "2%",
		width: "100%",
		backgroundColor: COLORS.flatlistElement1,
		flexDirection: "row",
	},
	listElementText: {
		fontSize: 12,
		textAlign: "center",
		color: "black",
	},
	exitButton: {
		// flex: 1.5,
		height: "8%",
		backgroundColor: COLORS.naranja,
		alignSelf: "flex-end",
		// height: "6%",
		width: "30%",
		// marginBottom: "3%",
		marginRight: "3%",
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.naranja,
	},
	textExitButton: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
});

const confirmModal = StyleSheet.create({
	container: {
		position: "absolute",
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
		// backgroundColor: "white",
		// borderRadius: 20,
	},
	modalContainer: {
		// height: "24%",
		height: "auto",
		// height: 200,
		marginVertical: "2%",
		width: "85%",
		paddingVertical: 10,
		paddingHorizontal: 10,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		// flex: 1,
		height: "auto",
		width: "95%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1
	},
	titleContainer: {
		flex: 0.6,
		// height: "4%",
		width: "100%",
		marginTop: "4%",
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	titleText: {
		fontSize: 22,
		marginBottom: 10,
		fontWeight: "bold",
		alignSelf: "flex-start",
		color: COLORS.black,
	},
	dataContainer: {
		flex: 1,
		width: "95%",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	dataText: {
		fontSize: 16,
		// marginBottom: 20,
		textAlign: "center",
		color: COLORS.black,
	},
	buttonsContainer: {
		// flex: 0.9,
		height: 35,
		width: "100%",
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
		// borderWidth: 1,
		// marginVertical: "3%",
	},
	confirmButton: {
		width: "40%",
		height: "100%",
		backgroundColor: COLORS.naranja,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.naranja,
	},
	confirmButtonText: {
		fontSize: 13,
		fontWeight: "bold",
		color: COLORS.white,
	},
	exitButton: {
		width: "40%",
		height: "100%",
		backgroundColor: COLORS.naranja,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.flatlistBackground,
	},
	exitButtonText: {
		fontSize: 13,
		fontWeight: "bold",
		color: COLORS.gray,
	},
});

export { historialModal, yearModal, signatureModal, confirmModal };
