import { StyleSheet } from "react-native";
import COLORS from "../../../../constants/colors";

const poliza = StyleSheet.create({
	container: {
		flex: 1,
		// width: "100%",
		justifyContent: "center",
		alignItems: "center",
		marginTop: "3%",
	},
	titleContainer: {
		height: "25%",
		width: "94%",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "black"
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.black,
	},
	contentContainer: {
		flex: 1,
		width: "92%",
		justifyContent: "flex-start",
		alignItems: "center",
	},
	polizaContainer: {
		height: "100%",
		width: "100%",
		justifyContent: "flex-end",
		alignItems: "center",
		// borderWidth: 1
	},
	cardContainer: {
		height: "80%",
		width: "100%",
		paddingTop: "8%",
		paddingBottom: "5%",
		padding: "2%",
		marginBottom: "1%",
		justifyContent: "center",
		alignItems: "flex-start",
		backgroundColor: COLORS.flatlistBackground,
		borderBottomLeftRadius: 12,
		borderBottomRightRadius: 12,
		borderTopRightRadius: 12,
		// borderWidth: 1,
	},
	cardHeaderContainer: {
		position: "absolute",
		height: "30%",
		width: "32%",
		bottom: "66.666666667%",
		justifyContent: "center",
		alignItems: "center",
		alignSelf: "flex-start",
		flexDirection: "row",
		// borderWidth: 1,
		// borderColor: "black",
		zIndex: 1,
	},
	cardIconContainer: {
		// flex: 2,
		// height: "100%",
		// width: "40%",
		// padding: 12,
		backgroundColor: COLORS.primary,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 50,
		zIndex: 2,
	},
	cardIcon: {
		color: COLORS.white,
	},
	cardTitleContainer: {
		flex: 5,
		height: "60%",
		right: "15%",
		backgroundColor: COLORS.flatlistElement2,
		justifyContent: "center",
		alignItems: "center",
		borderTopRightRadius: 50,
		borderBottomRightRadius: 50,
		zIndex: 1,
	},
	cardTitleTextContainer: {
		height: "100%",
		width: "80%",
		left: "4%",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	cardTitleText: {
		fontSize: 12,
		textAlign: "left",
		fontWeight: "bold",
		color: "black",
	},
	dataContainer: {
		// flex: 5,
		height: "58%",
		width: "95%",
		justifyContent: "center",
		alignItems: "flex-start",
		alignSelf: "center",
		marginTop: "5%",
		marginBottom: "2%",
		// borderWidth: 1
	},
	dataTextContainer: {
		flex: 2,
		width: "100%",
		justifyContent: "center",
		alignItems: "flex-start",
		marginVertical: "1%",
	},
	dataText: {
		fontSize: 12,
		textAlign: "left",
		fontWeight: "bold",
		color: COLORS.black,
	},
	dataContactsContainer: {
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
		left: "1%",
		marginTop: "2%",
        height: "25%",
        width: "100%",
		// borderWidth: 1,
	},
	dataContactContainer: {
		flex: 1,
		flexDirection: "row",
		height: "100%",
		// width: "31%",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 100,
		backgroundColor: COLORS.flatlistElement2,
        // marginRight: "2%",
	},
	dataContactIconContainer: {
        flex: 1.5,
        height: "100%",
        backgroundColor: COLORS.main,
        borderRadius: 100,
        justifyContent: "center",
		alignItems: "center",
    },
	dataContactIcon: {
        color: COLORS.white
    },
	dataContactTextContainer: {
        flex: 8,
		height: "85%",
        justifyContent: "center",
		alignItems: "center",
        // marginRight: "3%",
		right: "5%",
		// borderWidth: 1,
    },
	dataContactText: {
        fontSize: 11,
		fontWeight: "bold",
		color: COLORS.black,
    },
});

export { poliza };
