import { StyleSheet } from "react-native";
import COLORS from "../../../../constants/colors";

const poliza = StyleSheet.create({
	container: {
		// flex: 1,
		width: "92%",
		justifyContent: "flex-start",
		alignItems: "center",
		marginTop: "2%",
		// borderWidth: 1,
		borderColor: "blue",
	},
	titleText: {
		fontSize: 21,
		fontWeight: "bold",
		color: COLORS.black,
		alignSelf: "flex-start",
		marginBottom: "1%",
		// borderWidth: 1,
	},
	contentContainer: {
		// flex: 1,
		width: "100%",
		justifyContent: "flex-start",
		alignItems: "center",
		// borderWidth: 1,
	},
	cardHeaderContainer: {
		position: "absolute",
		height: "40%",
		width: "35%",
		// bottom: "66.666666667%",
		justifyContent: "flex-end",
		alignItems: "center",
		alignSelf: "flex-start",
		flexDirection: "row",
		// borderWidth: 1,
		// borderColor: "black",
		zIndex: 1,
	},
	cardIconContainer: {
		// flex: 2,
		// height: "100%",
		// width: "40%",
		// padding: 12,
		position: "absolute",
		left: 0,
		backgroundColor: COLORS.primary,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 50,
		zIndex: 2,
	},
	cardIcon: {
		color: COLORS.white,
	},
	cardTitleContainer: {
		// flex: 1,
		width: "75%",
		height: "75%",
		// right: "15%",
		backgroundColor: COLORS.flatlistElement2,
		justifyContent: "center",
		alignItems: "center",
		borderTopRightRadius: 50,
		borderBottomRightRadius: 50,
		zIndex: 1,
		// borderWidth: 1,
	},
	cardTitleText: {
		fontFamily: "Montserrat-SemiBold",
		fontSize: 13,
		textAlign: "left",
		// fontWeight: "bold",
		color: "black",
	},
	cardContainer: {
		// height: "80%",
		// height: 80,
		width: "100%",
		// paddingTop: "8%",
		paddingBottom: "3%",
		paddingHorizontal: "2%",
		// marginBottom: "1%",
		justifyContent: "flex-start",
		alignItems: "flex-start",
		backgroundColor: COLORS.flatlistBackground,
		borderBottomLeftRadius: 12,
		borderBottomRightRadius: 12,
		borderTopRightRadius: 12,
		// borderWidth: 1,
	},
	dataText: {
		marginVertical: "0.5%",
		marginHorizontal: "1%",
		fontFamily: "Montserrat-Medium",
		fontSize: 12,
		// borderWidth: 1,
	},
	dataContactsContainer: {
		width: "100%",
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginTop: "3%",
		// left: "1%",
		// borderWidth: 1,
	},
	dataContactContainer: {
		height: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 100,
		backgroundColor: COLORS.flatlistElement2,
		// borderWidth: 1,
	},
	dataContactIconContainer: {
		height: "100%",
		backgroundColor: COLORS.main,
		borderRadius: 100,
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
	},
	dataContactIcon: {
		color: COLORS.white,
	},
	dataContactTextContainer: {
		flex: 1,
		height: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
	},
	dataContactText: {
		fontSize: 11,
		fontWeight: "bold",
		color: COLORS.black,
	},
});

export { poliza };
