import { StyleSheet } from "react-native";
import COLORS, { BLACK, GRAY } from "../constants/colors";

const login = StyleSheet.create({
	backgroundContainer: {
		flex: 1,
		resizeMode: "cover",
		borderRadius: 15,
		overflow: "hidden",
		justifyContent: "center",
		alignItems: "center",
	},
	container: {
		// flex: 1,
		height: "100%",
		width: "100%",
		justifyContent: "space-between",
		alignItems: "center",
		// borderWidth: 1,
	},
	logoContainer: {
		alignSelf: "flex-start",
		top: 0,
		// flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
	},
	contentContainer: {
		bottom: 1,
		// flex: 1,
		// height: "50%",
		width: "100%",
		justifyContent: "flex-end",
		alignItems: "center",
		borderWidth: 1,
	},
	credentialsContainer: {
		flex: 21,
		// height: "42%",
		width: "90%",
		justifyContent: "space-between",
		alignItems: "center",
		// marginBottom: "1%",
		// borderWidth: 1,
		borderColor: "red",
	},
	fieldContainer: {
		height: "30%",
		width: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	fieldText: {
		left: "5%",
		fontWeight: "500",
		fontSize: 16,
		color: COLORS.black,
	},
	iconBox: {
		flex: 1,
		height: "100%",
		borderBottomLeftRadius: 24,
		borderTopLeftRadius: 24,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.naranja,
	},
	icon: {
		left: "4%",
		color: COLORS.white,
	},
	field: {
		flex: 7,
		height: "100%",
		backgroundColor: "white",
		// backgroundColor: COLORS.white,
		alignItems: "flex-start",
		justifyContent: "center",
		borderTopRightRadius: 24,
		borderBottomRightRadius: 24,
	},
	userInput: {
		paddingHorizontal: "5%",
		flex: 7,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		fontFamily: "Montserrat-Medium",
		fontSize: 14,
		color: COLORS.black,
		textTransform: "uppercase",
	},
	passEye: {
		position: "absolute",
		right: 12,
		flex: 1,
	},
	arrowContainer: {
		position: "absolute",
		top: "7%",
		right: "1%",
		justifyContent: "center",
		alignItems: "center",
		// alignSelf: "flex-end",
		height: "100%",
		width: "15%",
		// backgroundColor: "white"
		// flex: 1,
	},

	// Checkbox
	checkboxContainer: {
		// height: "10%",
		flex: 4,
		width: "90%",
		justifyContent: "center",
		alignItems: "flex-start",
		paddingLeft: "3%",
		marginTop: "1%",
		marginBottom: "4%",
		// borderWidth: 1,
	},
	checkboxText: {
		textDecorationLine: "none",
		fontFamily: "Montserrat-Regular",
	},

	// Login buttons
	buttonsContainer: {
		flex: 6,
		width: "90%",
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		marginBottom: "2%",
	},
	buttonContainer: {
		height: "100%",
		// width: "75%",
		alignItems: "center",
		justifyContent: "center",
		borderRadius: 24,
	},
	button: {
		height: "100%",
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
	},
	buttonText: {
		fontFamily: "Montserrat-Medium",
		fontSize: 15,
		color: "white",
	},
	// Reset link
	resetContainer: {
		// height: "8%",
		flex: 4,
		width: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		borderColor: "blue",
		// marginTop: "2%",
		marginBottom: "3%",
	},
	resetText: {
		fontFamily: "Montserrat-Regular",
		fontSize: 15,
		color: COLORS.black,
	},
	resetTextLink: {
		fontFamily: "Montserrat-Bold",
		fontSize: 15,
		color: COLORS.primary,
		marginLeft: 6,
	},
	version: {
		position: "absolute",
		bottom: 0,
		// left: "5%",
		// alignSelf: "flex-start",
		fontSize: 12,
		color: GRAY.g5,
	},
});

const reset = StyleSheet.create({
	backgroundContainer: {
		flex: 1,
		resizeMode: "cover",
		borderRadius: 15,
		overflow: "hidden",
		justifyContent: "center",
		alignItems: "center",
	},
	container: {
		// flex: 1,
		height: "100%",
		width: "100%",
		justifyContent: "space-between",
		alignItems: "center",
		// borderWidth: 1,
	},
	logoContainer: {
		alignSelf: "flex-start",
		top: 0,
		// flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
	},
	contentContainer: {
		bottom: 1,
		// flex: 1,
		// height: "50%",
		width: "100%",
		justifyContent: "flex-end",
		alignItems: "center",
		borderWidth: 1,
	},
	credentialsContainer: {
		flex: 22,
		// height: "42%",
		width: "90%",
		justifyContent: "space-between",
		alignItems: "center",
		// marginBottom: "1%",
		// borderWidth: 1,
		borderColor: "red",
		// borderWidth: 1
	},
	fieldContainer: {
		height: "23%",
		width: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
	},
	regionContainer: {
		flex: 6.5,
		width: "90%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		marginVertical: "2%",
		// borderWidth: 1,
	},
	fieldText: {
		left: "5%",
		fontFamily: "Montserrat-Medium",
		fontSize: 16,
		color: COLORS.black,
		// borderWidth: 1,
	},
	iconBox: {
		flex: 1,
		height: "100%",
		borderBottomLeftRadius: 24,
		borderTopLeftRadius: 24,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.naranja,
	},
	icon: {
		left: "4%",
		color: COLORS.white,
	},
	field: {
		flex: 7,
		height: "100%",
		backgroundColor: "white",
		// backgroundColor: COLORS.white,
		alignItems: "flex-start",
		justifyContent: "center",
		borderTopRightRadius: 24,
		borderBottomRightRadius: 24,
		// borderWidth: 1,
	},
	userInput: {
		paddingHorizontal: "5%",
		flex: 7,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		fontFamily: "Montserrat-Medium",
		fontSize: 14,
		color: COLORS.black,
		textTransform: "uppercase",
	},
	passEye: {
		position: "absolute",
		right: 12,
		flex: 1,
	},
	arrowContainer: {
		position: "absolute",
		top: "7%",
		right: "1%",
		justifyContent: "center",
		alignItems: "center",
		// alignSelf: "flex-end",
		height: "100%",
		width: "15%",
		// backgroundColor: "white"
		// flex: 1,
	},

	// Checkbox
	checkboxContainer: {
		// height: "10%",
		flex: 4,
		width: "90%",
		justifyContent: "center",
		alignItems: "flex-start",
		paddingLeft: "3%",
		marginTop: "1%",
		marginBottom: "4%",
		// borderWidth: 1,
	},
	checkboxText: {
		textDecorationLine: "none",
		fontFamily: "Montserrat-Regular",
	},
	// Login button
	buttonContainer: {
		flex: 5,
		// height: "12%",
		width: "90%",
		borderRadius: 24,
		// borderWidth: 1,
		marginBottom: "2%",
	},
	button: {
		height: "100%",
		width: "100%",
		alignItems: "center",
		justifyContent: "center",
	},
	buttonText: {
		fontFamily: "Montserrat-Medium",
		fontSize: 15,
		color: "white",
	},
	// Reset link
	resetContainer: {
		// height: "8%",
		flex: 3,
		width: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		borderColor: "blue",
		// marginTop: "2%",
		marginBottom: "3%",
	},
	resetText: {
		fontFamily: "Montserrat-Regular",
		fontSize: 15,
		color: COLORS.black,
	},
	resetTextLink: {
		fontFamily: "Montserrat-Bold",
		fontSize: 15,
		color: COLORS.primary,
		marginLeft: 6,
	},
	modal: {
		position: "absolute",
		height: "100%",
		width: "100%",
	},
});

const getGafeteStyle = (platform) => {
	return StyleSheet.create({
		container: {
			// height: "100%",
			width: "100%",
			justifyContent: "center",
			alignItems: "center",
			// borderWidth: 2,
			borderColor: "blue",
			backgroundColor: "white",
		},
		backgroundContainer: {
			position: "absolute",
			height: "100%",
			width: "100%",
			overflow: "hidden",
			justifyContent: "center",
			alignItems: "center",
		},
		whiteBackground: {
			// height: "35%",
			// borderWidth: 1,
			borderColor: "red",
			width: "100%",
		},
		arrowBackground: {
			// height: "65%",
			width: "100%",
			// borderWidth: 1,
			borderColor: "green",
			justifyContent: "flex-end",
			alignItems: "center",
		},
		content: {
			height: "100%",
			width: "100%",
		},
		contentContainer: {
			position: "absolute",
			height: "100%",
			width: "100%",
			justifyContent: "flex-start",
			alignItems: "center",
			// paddingTop: statusBarHeight,
		},
		topContainer: {
			position: "absolute",
			width: "100%",
			top: 0,
			// borderWidth: 2,
			borderColor: "purple",
		},
		bottomContainer: {
			position: "absolute",
			width: "100%",
			bottom: 0,
			// borderWidth: 1,
		},
		dataContainer: {
			// flex: 1,
			width: "100%",
			justifyContent: "center",
			alignItems: "center",
			// borderWidth: 1,
			// borderColor: "white",
		},
		logo: {
			height: "50%",
			width: "40%",
		},
		logoQR: {
			position: "absolute",
			height: "9%",
			width: "9%",
			alignSelf: "center",
			zIndex: 2,
		},
		name: { fontSize: 18 },
		imageContainer: {
			height: "100%",
			width: "100%",
			padding: 5,
			// borderRadius: 40,
			justifyContent: "center",
			alignItems: "center",
			// borderWidth: 1,
			borderColor: "white",
			backgroundColor: "white",
			shadowOffset: { width: 2, height: 4 }, // X: 0, Y: 4
			shadowOpacity: 0.4,
			shadowRadius: 5,
		},
		// imageContainer: {
		// 	height: "100%",
		// 	width: "100%",
		// 	padding: 5,
		// 	// borderRadius: 40,
		// 	justifyContent: "center",
		// 	alignItems: "center",
		// 	borderWidth: 1,
		// 	borderColor: "white",
		// 	backgroundColor: "white",
		// 	// iOS Shadow
		// 	shadowColor: "#000",

		// 	// Android Shadow
		// 	elevation: 50,
		// },
		imageContainerShadow: {
			position: "absolute",
			height: "100%",
			width: "100%",
			// borderRadius: 40,
			backgroundColor: "#000",
			top: 4,
			left: 4,
			opacity: 0.1,
		},
		image: {
			height: "100%",
			// height: 150,
			// width: 150,
			width: "100%",
			// borderRadius: 40,
			// borderRadius: 100,
			overflow: "hidden",
		},
		jobDescription: {
			fontFamily: "Montserrat-Regular",
			fontSize: 22,
			color: "white",
		},
		employeeNumberBackground: {
			position: "absolute",
			height: "100%",
			width: "60%",
			borderTopLeftRadius: 50,
			borderBottomRightRadius: 50,
			backgroundColor: "black",
			opacity: 0.4,
		},
		employeeNumber: {
			fontFamily: "Roboto-Medium",
			fontSize: 22,
			color: "white",
			letterSpacing: 3,
			// marginBottom: "2%"
		},
		QR: {
			height: "100%",
			width: "100%",
			// justifyContent: "center",
			// alignItems: "center",
		},
		categoryTitlesContainer: {
			height: "40%",
			width: "100%",
			flexDirection: "row",
			justifyContent: "center",
			alignItems: "center",
			opacity: 0.9,
		},
		categoriesContainer: {
			height: "60%",
			width: "100%",
			flexDirection: "row",
			justifyContent: "center",
			alignItems: "center",
			opacity: 0.8,
			// borderWidth: 1,
			borderColor: "white",
		},
		category: {
			// height: "100%",
			fontFamily: "Montserrat-Light",
			fontSize: 17,
			color: "white",
			// borderWidth: 1,
			borderColor: "white",
			textAlign: "center",
		},
		categoryDataContainer: {
			width: "100%",
			justifyContent: "center",
			alignItems: "center",
		},
		categoryData: {
			fontFamily: "Roboto-Regular",
			fontSize: 18,
			color: "white",
			// borderWidth: 1,
			borderColor: "white",
		},
		company: {
			fontFamily: "Montserrat-LightItalic",
			fontSize: 10,
			color: "white",
		},
		generadoShadowContainer: {
			height: "100%",
			width: "35%",
			justifyContent: "center",
			alignItems: "flex-start",
			backgroundColor: BLACK.b2,
			borderTopRightRadius: 40,
			borderBottomRightRadius: 40,
			// borderWidth: 1,
		},
		generadoContainer: {
			height: "100%",
			width: "92%",
			paddingLeft: "8%",
			justifyContent: "center",
			alignItems: "flex-start",
			backgroundColor: BLACK.b4,
			borderTopRightRadius: 40,
			borderBottomRightRadius: 40,
		},
		generado: {
			fontFamily: "Montserrat-Bold",
			fontSize: 13,
			color: "white",
		},
		generadoDataContainer: {
			height: "100%",
			width: "65%",
			flexDirection: "row",
			paddingHorizontal: "3%",
			justifyContent: "space-between",
			alignItems: "center",
			// borderWidth: 1,
			borderColor: "white",
		},
		generadoData: {
			fontFamily: "Montserrat-Regular",
			fontSize: 14,
			color: "white",
		},
		backButton: {
			position: "absolute",
			top: 0,
			// top: statusBarHeight,
			left: 0,
			height: platform === "ios" ? 50 : 70,
			width: 70,
			justifyContent: "center",
			alignItems: "center",
			zIndex: 2,
			// borderWidth: 1
		},
	});
};

export { login, reset, getGafeteStyle };
