import { StyleSheet } from "react-native";
import COLORS from "../../../../constants/colors";

const familia = StyleSheet.create({
	familiaContainer: {
		flex: 1,
		// width: "100%",
		justifyContent: "center",
		alignItems: "center",
		marginTop: "3%",
		// borderWidth: 1,
		// borderColor: "black"
	},
	familiaTitleContainer: {
		height: "25%",
		width: "94%",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "black"
	},
	familiaTitleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.black,
	},
	familiaAddButton: {
		flex: 0.3,
		height: "75%",
		marginLeft: "4%",
		backgroundColor: COLORS.naranja,
		justifyContent: "center",
		alignContent: "center",
		borderRadius: 50,
	},
	familiaAddButtonText: {
		fontSize: 10,
		fontWeight: "bold",
		color: COLORS.white,
		alignSelf: "center",
	},
	familiaContentContainer: {
		flex: 1,
		width: "92%",
		justifyContent: "flex-start",
		alignItems: "center",
	},
	familiaCardContainer: {
		height: "80%",
		width: "100%",
		paddingTop: "8%",
		padding: "4%",
		marginBottom: "1%",
		justifyContent: "center",
		alignItems: "flex-start",
		backgroundColor: COLORS.flatlistBackground,
		borderBottomLeftRadius: 12,
		borderBottomRightRadius: 12,
		borderTopRightRadius: 12,
	},
	familiaMemberContainer: {
		height: "100%",
		width: "100%",
		justifyContent: "flex-end",
		alignItems: "center",
	},
	familiaMemberNameContainer: {
		position: "absolute",
		height: "30%",
		width: "32%",
		bottom: "66.666666667%",
		justifyContent: "center",
		alignItems: "center",
		alignSelf: "flex-start",
		flexDirection: "row",
		// borderWidth: 1,
		// borderColor: "black",
		zIndex: 1,
	},
	familiaMemberIconContainer: {
		// flex: 2,
		// height: "100%",
		// width: "40%",
		// padding: 12,
		backgroundColor: COLORS.primary,
		justifyContent: "center",
		alignItems: "center",
		borderRadius: 50,
		zIndex: 2,
	},
	familiaMemberIcon: {
		color: COLORS.white,
	},
	familiaMemberDataContainer: {
		flex: 5,
		height: "60%",
		right: "15%",
		backgroundColor: COLORS.flatlistElement2,
		justifyContent: "center",
		alignItems: "center",
		borderTopRightRadius: 50,
		borderBottomRightRadius: 50,
		zIndex: 1,
	},
	familiaMemberDataTextContainer: {
		height: "100%",
		width: "84%",
		left: "3%",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	familiaMemberDataText: {
		fontSize: 11,
		marginLeft: 4,
		textAlign: "left",
		fontWeight: "bold",
		color: COLORS.black,
	},
	familiaRemoveButton: {
		position: "absolute",
		width: "20%",
		height: "16%",
		bottom: "67%",
		alignSelf: "flex-end",
		borderBottomLeftRadius: 12,
		borderTopRightRadius: 12,
		backgroundColor: COLORS.familiaRemove,
		justifyContent: "center",
		alignItems: "center",
		zIndex: 1,
	},
	familiaRemoveButtonText: {
		fontSize: 10,
		fontWeight: "bold",
		color: COLORS.white,
	},
});

const tallas = StyleSheet.create({
	container: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
		marginTop: "3%",
	},
	titleContainer: {
		flex: 1,
		width: "94%",
		flexDirection: "row",
		justifyContent: "flex-start",
		alignItems: "center",
	},
	titleText: {
		fontSize: 20,
		fontWeight: "bold",
		color: COLORS.black,
	},
	prendasContainer: {
		flex: 3,
		flexDirection: "row",
		justifyContent: "space-evenly",
		alignItems: "center",
		paddingHorizontal: "2%",
	},
	prendaContainer: {
		flex: 1,
		height: "100%",
		flexDirection: "row",
		justifyContent: "center",
		alignItems: "center",
		
		// borderWidth: 1,
	},
	prendaIconContainer: {
		height: "60%",
		width: "40%",
		left: 6,
		backgroundColor: COLORS.primary,
		borderRadius: 50,
		justifyContent: "center",
		alignItems: "center",
		zIndex: 1,
	},
	prendaIcon: {
		color: COLORS.white,
	},
	prendaDataContainer: {
		height: "30%",
		width: "70%",
		justifyContent: "center",
		alignItems: "flex-end",
		backgroundColor: COLORS.flatlistElement2,
		borderBottomRightRadius: 50,
		borderTopRightRadius: 50,
		// borderWidth: 1,
	},
	prendaDataTextContainer: {
		height: "84%",
		width: "90%",
		paddingHorizontal: "3%",
		right: 4,
		justifyContent: "center",
		alignItems: "center",
		// borderWidth: 1,
		// borderColor: "black"
	},
	prendaDataText: {
		// height: "100%",
		width: "100%",
		textAlign: "center",
		// textAlignVertical: "center",
		fontSize: 11,
		fontWeight: "bold",
		color: COLORS.black,
		// borderWidth: 1,
	},
	button: {
		height: "75%",		
		width: "24%",
		marginLeft: "5%",
		backgroundColor: COLORS.naranja,
		justifyContent: "center",
		alignContent: "center",
		borderRadius: 50,
	},
	buttonText: {
		fontSize: 10,
		fontWeight: "bold",
		color: COLORS.white,
		alignSelf: "center",
	},
});

const domicilioModal = StyleSheet.create({
	container: {
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "flex-start",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
		// borderRadius: 20,
	},
	modalContainer: {
		flex: 1,
		marginVertical: "2%",
		width: "90%",
		justifyContent: "flex-start",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 0.95)",
		borderRadius: 20,
	},
	titleContainer: {
		flex: 4,
		backgroundColor: COLORS.naranja,
		// height: "4%",
		width: "95%",
		marginTop: "2%",
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
	},
	textTitle: {
		fontSize: 15,
		fontWeight: "bold",
		color: COLORS.white,
	},
});

const confirmModal = StyleSheet.create({
	container: {
		position: "absolute",
		flex: 1,
		justifyContent: "center",
		alignItems: "center",
	},
	backgroundContainer: {
		flex: 1,
		width: "100%",
		justifyContent: "center",
		alignItems: "center",
		// backgroundColor: "rgba(255,255,255, 0.9)",
		backgroundColor: "rgba(0, 0, 0, 0.4)",
		// borderRadius: 20,
	},
	modalContainer: {
		height: "24%",
		marginVertical: "2%",
		width: "80%",
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: "rgba(242, 242, 242, 1)",
		borderRadius: 25,
	},
	contentContainer: {
		flex: 1,
		width: "90%",
		justifyContent: "center",
		alignItems: "center",
	},
	titleContainer: {
		flex: 0.6,
		// height: "4%",
		width: "100%",
		marginTop: "4%",
		justifyContent: "flex-start",
		alignItems: "flex-start",
	},
	titleText: {
		fontSize: 22,
		fontWeight: "bold",
		color: COLORS.black,
	},
	dataContainer: {
		flex: 1,
		width: "95%",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	dataText: {
		fontSize: 16,
		textAlign: "center",
		color: COLORS.black,
	},
	buttonsContainer: {
		flex: 0.9,
		width: "100%",
		flexDirection: "row",
		justifyContent: "space-around",
		alignItems: "center",
		// marginVertical: "3%",
	},
	confirmButton: {
		width: "40%",
		height: "52%",
		backgroundColor: COLORS.naranja,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.naranja,
	},
	confirmButtonText: {
		fontSize: 13,
		fontWeight: "bold",
		color: COLORS.white,
	},
	exitButton: {
		width: "40%",
		height: "52%",
		backgroundColor: COLORS.naranja,
		borderRadius: 20,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: COLORS.flatlistBackground,
	},
	exitButtonText: {
		fontSize: 13,
		fontWeight: "bold",
		color: COLORS.gray,
	},
});

export { familia, tallas, domicilioModal, confirmModal };
